[supervisord]
nodaemon=true
logfile=/home/LogFiles/supervisord.log

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

; -------- Web --------
[program:web]
command=gunicorn -c gunicorn.conf.py DSS:app
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stdout_logfile=/home/LogFiles/gunicorn_out.log
stderr_logfile=/home/LogFiles/gunicorn_err.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

; -------- Workers (2) --------
[program:worker1]
command=rq worker -u %(ENV_REDIS_URL)s --path . default -v
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stdout_logfile=/home/LogFiles/rq1_out.log
stderr_logfile=/home/LogFiles/rq1_err.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:worker2]
command=rq worker -u %(ENV_REDIS_URL)s --path . default -v
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stdout_logfile=/home/LogFiles/rq2_out.log
stderr_logfile_maxbytes=0
stderr_logfile=/home/LogFiles/rq2_err.log
